apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-gitops-root-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/k8s-gitops
    targetRevision: staging
    path: argocd/apps
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
