apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: k8s-gitops-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.clusterSecretStore.name }}
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_PASSWORD
      remoteRef:
        key: /{{ .Values.project }}/{{ .Values.environment }}/mongodb/credentials
        property: password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: /{{ .Values.project }}/{{ .Values.environment }}/redis/password
        property: password
